export default {
  FETCHING_RECIPES: "recipes/FETCHING_RECIPES",
  SUCCESS_FECTH_RECIPES: "recipes/SUCCESS_FETCH_RECIPES",
  FAILURE_RECIPES: "recipes/FAILURE_FETCH_RECIPES",
  CREATING_RECIPE: "recipes/CREATING_RECIPE",
  SUCCESS_CREATED_RECIPE: "recipes/SUCCESS_CREATED_RECIPE",
  FAILURE_CREATE_RECIPE: "recipes/FAILURE_CREATE_RECIPE",
};
