export default {
  FETCHING_RECIPES: "recipes/FETCHING_RECIPES",
  SUCCESS_FECTH_RECIPES: "recipes/SUCCESS_FETCH_RECIPES",
  FAILURE_RECIPES: "recipes/FAILURE_FETCH_RECIPES",
  CREATING_RECIPE: "recipes/CREATING_RECIPE",
  SUCCESS_CREATED_RECIPE: "recipes/SUCCESS_CREATED_RECIPE",
  FAILURE_CREATE_RECIPE: "recipes/FAILURE_CREATE_RECIPE",
  FETCHING_RECIPE: "recipes/FETCHING_RECIPE",
  SUCCESS_FECTH_RECIPE: "recipes/SUCCESS_FECTH_RECIPE",
  FAILURE_FETCH_RECIPE: "recipes/FAILURE_FETCH_RECIPE",
  CREATING_IMAGE_RECIPE: "recipes/CREATING_IMAGE_RECIPE",
  SUCCESS_CREATED_IMAGE: "recipes/SUCCESS_CREATED_IMAGE",
  FAILURE_CREATE_IMAGE: "recipes/FAILURE_CREATE_IMAGE",
};
